/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentContainer: typeof import('./src/components/core/ContentContainer.vue')['default']
    HeaderComponent: typeof import('./src/components/core/HeaderComponent.vue')['default']
    MainContainer: typeof import('./src/components/core/MainContainer.vue')['default']
    Navbar: typeof import('./src/components/core/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
